controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0  # Reduced from 50.0

    # VELOCITY LIMITS - Add these parameters:
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.2         # 🔧 Limit max speed
        min_velocity: -0.2
        has_acceleration_limits: true
        max_acceleration: 0.8     # 🔧 Smooth acceleration
        min_acceleration: -0.8
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.2         # 🔧 Limit turning speed
        min_velocity: -0.2
        has_acceleration_limits: true
        max_acceleration: 1.5     # 🔧 Smooth turning
        min_acceleration: -1.5

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.322
    wheel_radius: 0.034

    use_stamped_vel: true